### ISSUE TITLE
Gradle Wrapper is missing

### ISSUE THREAD

**Issue by jaredwhitney** [RMHSProgrammingClub/Gravity-Jumper#1]

**Comment by jakebacker** [comment]
#41e90a9

**Comment by jakebacker** [comment]
https://github.com/RMHSProgrammingClub/Gravity-Jumper/commit/41e90a94ff53a7d0c77498be151e7bddae917baa

**Comment by jaredwhitney** [comment]
Fixed in b897b549b56974f051689c3904404fb2f529478e
